### ISSUE TITLE
Store charts to cloud storage

### ISSUE THREAD

**Issue by proteus1121** [leafchild0/chart-desk#22]

**Comment by proteus1121** [comment]
@leafchild0 When the user uploads chart we can try to parse chart metadata but instead of saving the chart we can find an existing chart in db and reuse the url.
But it causes a problem when one chart could be related to multiple users. So what solution be better, duplicated chart records with a foreign key to the user or an extra table chart-user? Also, we shouldn't forget that different users can use different versions of these chats.

**Comment by leafchild0** [comment]
My opinion is an extra chart option. This is more flexible, we can have different version, updated ones, etc
